# Generated by Django 5.0.2 on 2024-02-19 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePicture', models.ImageField(null=True, upload_to='', verbose_name='Profile Picture')),
                ('firstName', models.CharField(max_length=255, null=True, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=255, null=True, verbose_name='Last Name')),
                ('dateOfBirth', models.DateField(null=True, verbose_name='Date of Birth')),
                ('age', models.IntegerField(default=0, null=True, verbose_name='Age of Alumni')),
                ('mobileNumber', models.CharField(max_length=13, null=True, verbose_name='Mobile Number')),
                ('emailID', models.EmailField(max_length=254, null=True, verbose_name='Email Address')),
                ('role', models.CharField(max_length=255, null=True, verbose_name='Role')),
                ('location', models.CharField(max_length=255, null=True, verbose_name='Location')),
                ('followers', models.ManyToManyField(blank=True, to='main.account')),
                ('following', models.ManyToManyField(blank=True, to='main.account')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, null=True, verbose_name='Text')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.account')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startYear', models.CharField(max_length=4, null=True, verbose_name='Start Year')),
                ('department', models.CharField(choices=[('Computer Science and Engineering', 'Computer Science and Engineering')], max_length=100, null=True, verbose_name='Department')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.account')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.account')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Image')),
                ('caption', models.CharField(max_length=255, null=True, verbose_name='Caption')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.account')),
                ('comments', models.ManyToManyField(blank=True, to='main.comment')),
                ('likes', models.ManyToManyField(blank=True, to='main.like')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('Computer Science and Engineering', 'Computer Science and Engineering')], max_length=100, null=True, verbose_name='Branch')),
                ('section', models.CharField(choices=[('None', 'None'), ('Alpha', 'Alpha'), ('Beta', 'Beta'), ('Gamma', 'Gamma')], max_length=100, null=True, verbose_name='Section')),
                ('batch', models.CharField(max_length=100, null=True, verbose_name='Batch')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.account')),
            ],
        ),
    ]
