# Generated by Django 5.0.2 on 2024-02-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.CharField(max_length=2555, null=True, verbose_name='Bio'),
        ),
    ]
