# Generated by Django 4.2.7 on 2024-02-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('direct', 'direct'), ('group', 'group')], default='direct', max_length=255),
        ),
    ]
